project:
  type: website
  output-dir: docs

website:
  title: " "
  navbar:
    left:
      - href: index.qmd
        text: PSCI 3200 Final Project

format:
  html:
    theme: cosmo
    font-family: sans-serif;
    css: styles.css
    toc: true

editor: visual

